apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsofapps
spec:
  project: default
  source:
    repoURL: https://github.com/soura49/argocd.git
    targetRevision: HEAD
    path: argo-applications
  destination:
    server: https://kubernetes.default.svc
