apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/soura49/argocd.git
    targetRevision: HEAD
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: default
