apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: istio-system
spec:
  project: default
  source:
    chart: istio
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.19.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
